import type { CollectionEntry, Opportunity } from "@/types/tcg";

export const DEMO_COLLECTION: CollectionEntry[] = [
  {
    id: "demo-1",
    cardId: "base1-4",
    name: "Charizard",
    image: "https://assets.tcgdex.net/en/base/base1/4",
    setName: "Base Set",
    number: "4",
    rarity: "Rare Holo",
    quantity: 1,
    paid: 890,
    market: 1240,
    condition: "LP",
    addedAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "demo-2",
    cardId: "base1-58",
    name: "Pikachu",
    image: "https://assets.tcgdex.net/en/base/base1/58",
    setName: "Base Set",
    number: "58",
    rarity: "Common",
    quantity: 2,
    paid: 75,
    market: 112,
    condition: "NM",
    addedAt: "2026-08-04T10:00:00.000Z",
  },
  {
    id: "demo-3",
    cardId: "sv03.5-151",
    name: "Mew ex",
    image: "https://assets.tcgdex.net/en/sv/sv03.5/151",
    setName: "151",
    number: "151",
    rarity: "Double Rare",
    quantity: 1,
    paid: 85,
    market: 129,
    condition: "NM",
    addedAt: "2026-08-07T10:00:00.000Z",
  },
];

export const DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-1",
    title: "Charizard — Base Set",
    subtitle: "LP · oferta abaixo da referência",
    image: "https://assets.tcgdex.net/en/base/base1/4",
    price: 920,
    market: 1240,
    score: 93,
    source: "Marketplace monitorado",
  },
  {
    id: "opp-2",
    title: "Mew ex — 151",
    subtitle: "NM · boa liquidez",
    image: "https://assets.tcgdex.net/en/sv/sv03.5/151",
    price: 96,
    market: 129,
    score: 88,
    source: "Loja monitorada",
  },
  {
    id: "opp-3",
    title: "Pikachu — Base Set",
    subtitle: "NM · desconto moderado",
    image: "https://assets.tcgdex.net/en/base/base1/58",
    price: 86,
    market: 112,
    score: 79,
    source: "Marketplace monitorado",
  },
];
